Install Spring Boot BOM from source when not present in Maven Central
When updating the boosters as part of the community release process,
we usually don't wait for the BOM to propagate to Maven Central.
That can cause the booster tests to fail for no fault of their own.
In such cases we fall back to downloading the BOM from Github
and installing it locally

Implements: SB-739

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -39,9 +39,29 @@ jobs:
             - spring-boot-cache-booster-{{ .Branch }}
             - spring-boot-cache-booster
 
-      # Will download all deps needed into .m2
-      # Need to exclude tests since Maven will fail. See https://stackoverflow.com/q/14694139/2504224
-      - run: ./mvnw -s .circleci/settings.xml dependency:go-offline --projects '!tests'
+      - run:
+          name: Install Maven dependencies locally
+          command: |
+            # Need to exclude tests since Maven will fail. See https://stackoverflow.com/q/14694139/2504224
+            ./mvnw -q -s .circleci/settings.xml dependency:go-offline --projects '!tests'
+            if ! ./mvnw -s .circleci/settings.xml dependency:go-offline --projects '!tests'; then
+                bom_version=$(grep -oPm1 "(?<=<spring-boot.bom.version>)[^<]+" pom.xml)
+                echo "Need to checkout the Spring Boot BOM by checking it out from Github using version: ${bom_version}"
+
+                pushd /tmp > /dev/null
+                #Clone the BOM from Github, checkout the tag that matches the BOM version and install it locally
+                git clone https://github.com/snowdrop/spring-boot-bom.git
+                cd spring-boot-bom
+                git fetch --all --tags --prune
+                git checkout tags/${bom_version}
+                mvn install
+
+                echo "Installed BOM from source"
+
+                popd > /dev/null
+                #Re-execute command since the BOM has now been installed to the local .m2 directory
+                ./mvnw -q -s .circleci/settings.xml dependency:go-offline --projects '!tests';
+            fi
 
 
       - save_cache:
